
CREATE TABLE t_p8923173_afisha_light_app.places (
  id          SERIAL PRIMARY KEY,
  vk_group_id INTEGER NOT NULL DEFAULT 0,
  name        TEXT NOT NULL DEFAULT '',
  city        TEXT NOT NULL DEFAULT '',
  address     TEXT NOT NULL DEFAULT '',
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE t_p8923173_afisha_light_app.events
  ADD COLUMN IF NOT EXISTS tags          TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS place_id      INTEGER,
  ADD COLUMN IF NOT EXISTS schedule_type TEXT NOT NULL DEFAULT 'once',
  ADD COLUMN IF NOT EXISTS show_dates    BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS priority      SMALLINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS link1_url     TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS link1_label   TEXT NOT NULL DEFAULT 'Билеты',
  ADD COLUMN IF NOT EXISTS link2_url     TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS link2_label   TEXT NOT NULL DEFAULT 'Подробнее',
  ADD COLUMN IF NOT EXISTS admin_notes   TEXT NOT NULL DEFAULT '';
